/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
static yyconst short int yy_acclist[111] =
    {   0,
       67,   65,   66,   61,   65,   66,   62,   66,   63,   65,
       66,   65,   66,   47,   65,   66,   48,   65,   66,   54,
       65,   66,   52,   65,   66,   51,   65,   66,   53,   65,
       66,   55,   65,   66,   58,   65,   66,   56,   65,   66,
       46,   65,   66,   57,   65,   66,   60,   65,   66,   49,
       65,   66,   50,   65,   66,   65,   66,   65,   66,   61,
       59,   58,   60,   35,   37,   32,    8,    4,    2,   12,
        7,   45,   30,   43,   28,   64,   26,   25,   31,   38,
       23,   22,   21,   16,    9,   24,   10,   39,   40,   41,
       18,   19,   33,   17,   20,   13,   15,    5,   27,   64,

       34,   36,    3,    1,   11,    6,   44,   29,   42,   14
    } ;

static yyconst short int yy_accept[114] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   12,   14,   17,
       20,   23,   26,   29,   32,   35,   38,   41,   44,   47,
       50,   53,   56,   58,   60,   61,   61,   62,   63,   64,
       64,   64,   64,   64,   64,   64,   64,   65,   66,   67,
       68,   69,   70,   71,   72,   73,   74,   75,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   77,   78,   79,   80,
       81,   82,   83,   84,   85,   86,   87,   88,   89,   90,
       91,   92,   93,   94,   95,   96,   97,   98,   99,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  100,  101,

      101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
      110,  111,  111
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    9,   10,   11,    1,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,    1,
       16,    1,    1,    1,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
        1,    1,    1,    1,   17,    1,   17,   17,   17,   17,

       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   18,    1,   19,    1,    1,   20,   21,   22,
        1,   23,    1,    1,    1,    1,    1,    1,    1,   24,
        1,    1,   25,    1,    1,   26,   27,   28,   29,   30,
        1,    1,   31,   32,   33,   34,   35,    1,   36,   37,
        1,   38,    1,   39,   40,    1,   41,    1,    1,    1,
       42,   43,   44,   45,    1,   46,   47,    1,   48,    1,
        1,   49,    1,   50,   51,    1,   52,   53,   54,   55,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,   56,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   57,   58,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[116] =
    {   0,
        0,   57,  130,  155,  127,  155,  155,  122,  155,  155,
      155,  155,  155,  155,  155,  113,  155,  155,  155,    7,
      155,  155,    0,   89,  121,  117,  155,  108,    9,    0,
       71,   67,    2,   93,    4,   51,   57,   55,  155,  155,
       54,   53,   52,   51,   50,   49,   48,  155,   61,   63,
       96,   75,   58,   53,    1,    0,   47,   45,   44,   43,
       41,   39,   38,   32,   31,    0,  155,  155,  155,  155,
      155,  155,  155,  155,    1,  155,  155,  155,  155,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,   29,
       28,   27,   25,   24,   18,   17,   16,   15,    0,    3,

      155,  155,  155,  155,  155,  155,  155,  155,  155,   10,
      155,  155,  150,  152,    0
    } ;

static yyconst short int yy_def[116] =
    {   0,
      113,  113,  112,  112,  112,  112,  112,  114,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  114,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  115,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  115,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,    0,  112,  112,  112
    } ;

static yyconst short int yy_nxt[214] =
    {   0,
       99,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   29,
      112,   29,  112,   29,   30,   29,   47,   48,   86,   31,
       32,   33,   44,   34,   35,   87,  111,  110,   45,  109,
      108,  107,  106,   37,   38,   39,   88,   40,  105,  104,
       41,  103,  102,  101,   89,   23,  100,   24,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   49,   50,   51,   52,
       98,   97,   53,   67,   68,   69,   54,   96,   95,   55,
       94,   56,   93,   92,   91,   70,   90,   71,   85,   84,

       83,   72,   73,   66,   65,   64,   63,   62,   61,   60,
       59,   58,   23,   57,   24,   74,   75,   46,   43,   42,
       28,   27,   25,   76,   36,   28,   27,   77,   25,  112,
      112,  112,  112,   78,   79,   80,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,   81,   82,
        4,    4,   26,   26,    3,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112
    } ;

static yyconst short int yy_chk[214] =
    {   0,
      115,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   20,
        0,   29,    0,   20,   23,   29,   35,   35,   55,   23,
       23,   23,   33,   23,   23,   55,  110,  100,   33,   98,
       97,   96,   95,   30,   30,   30,   56,   30,   94,   93,
       30,   92,   91,   90,   56,    1,   75,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,   36,   36,   36,   36,
       65,   64,   36,   50,   50,   50,   36,   63,   62,   36,
       61,   36,   60,   59,   58,   50,   57,   50,   54,   53,

       52,   50,   50,   49,   47,   46,   45,   44,   43,   42,
       41,   38,    2,   37,    2,   51,   51,   34,   32,   31,
       28,   26,   25,   51,   24,   16,    8,   51,    5,    3,
        0,    0,    0,   51,   51,   51,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   51,   51,
      113,  113,  114,  114,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "emoji_flow.l"
#define INITIAL 0
#line 2 "emoji_flow.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Token definitions for Bison compatibility */
#define START       256
#define END         257
#define BLOCK       258
#define SEMI        259
#define TASK        260
#define RUN         261
#define WAIT        262
#define LOOP        263
#define STOP        264
#define RETRY       265
#define IF          266
#define ELSE        267
#define AND         268
#define OR          269
#define NOT         270
#define GT          271
#define LT          272
#define EQ          273
#define INPUT       274
#define OUTPUT      275
#define LOG         276
#define ALERT       277
#define OPEN        278
#define CLOSE       279
#define FILE_TOK    280
#define DELETE      281
#define WRITE       282
#define READ        283
#define TIME        284
#define SCHEDULE    285
#define NEXT        286
#define PREV        287
#define ID          288
#define INT_TYPE    289
#define STRING_TYPE 290
#define TRUE_VAL    291
#define FALSE_VAL   292
#define ASSIGN      293
#define ERROR_TOK   294
#define NUMBER      295
#define STRING_LIT  296
#define IDENTIFIER  297
#define LPAREN      298
#define RPAREN      299
#define LBRACE      300
#define RBRACE      301
#define COMMA       302
#define PLUS        303
#define MINUS       304
#define MULTIPLY    305
#define DIVIDE      306
#define COLON       307
#define NEWLINE     308

int line_num = 1;
int col_num = 1;
FILE *output_file;

/* Function to output token for Bison */
void output_token(int token, const char* token_name, const char* lexeme) {
    fprintf(output_file, "<%s, %s>\n", token_name, lexeme);
    printf("Line %d, Col %d: %-15s -> %s\n", line_num, col_num, lexeme, token_name);
}

/* UTF-8 multibyte character patterns */
#line 548 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 83 "emoji_flow.l"


    /* ============ Program Structure ============ */

    /* START: ▶️ (U+25B6 U+FE0F)*/
#line 705 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 113 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 155 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 88 "emoji_flow.l"
{ output_token(START, "START", yytext); col_num += 2; return START; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "emoji_flow.l"
{ output_token(RUN, "RUN", yytext); col_num += 1; return RUN; }
	YY_BREAK
/* END: ⏹️ (U+23F9 U+FE0F) */
case 3:
YY_RULE_SETUP
#line 92 "emoji_flow.l"
{ output_token(END, "END", yytext); col_num += 2; return END; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 93 "emoji_flow.l"
{ output_token(END, "END", yytext); col_num += 1; return END; }
	YY_BREAK
/* BLOCK: 🧱 (U+1F9F1) */
case 5:
YY_RULE_SETUP
#line 96 "emoji_flow.l"
{ output_token(BLOCK, "BLOCK", yytext); col_num += 1; return BLOCK; }
	YY_BREAK
/* ============ Tasks & Actions ============ */
/* TASK: ⚙️ (U+2699 U+FE0F) */
case 6:
YY_RULE_SETUP
#line 101 "emoji_flow.l"
{ output_token(TASK, "TASK", yytext); col_num += 2; return TASK; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 102 "emoji_flow.l"
{ output_token(TASK, "TASK", yytext); col_num += 1; return TASK; }
	YY_BREAK
/* WAIT: ⏳ (U+23F3) */
case 8:
YY_RULE_SETUP
#line 105 "emoji_flow.l"
{ output_token(WAIT, "WAIT", yytext); col_num += 1; return WAIT; }
	YY_BREAK
/* LOOP: 🔁 (U+1F501) */
case 9:
YY_RULE_SETUP
#line 108 "emoji_flow.l"
{ output_token(LOOP, "LOOP", yytext); col_num += 1; return LOOP; }
	YY_BREAK
/* STOP: 🔚 (U+1F51A) */
case 10:
YY_RULE_SETUP
#line 111 "emoji_flow.l"
{ output_token(STOP, "STOP", yytext); col_num += 1; return STOP; }
	YY_BREAK
/* RETRY: ♻️ (U+267B U+FE0F) */
case 11:
YY_RULE_SETUP
#line 114 "emoji_flow.l"
{ output_token(RETRY, "RETRY", yytext); col_num += 2; return RETRY; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 "emoji_flow.l"
{ output_token(RETRY, "RETRY", yytext); col_num += 1; return RETRY; }
	YY_BREAK
/* ============ Conditions & Logic ============ */
/* IF: 🤔 (U+1F914) */
case 13:
YY_RULE_SETUP
#line 120 "emoji_flow.l"
{ output_token(IF, "IF", yytext); col_num += 1; return IF; }
	YY_BREAK
/* ELSE: 🔁❓ (U+1F501 U+2753) - LOOP followed by question mark */
case 14:
YY_RULE_SETUP
#line 123 "emoji_flow.l"
{ output_token(ELSE, "ELSE", yytext); col_num += 2; return ELSE; }
	YY_BREAK
/* AND: 🤝 (U+1F91D) */
case 15:
YY_RULE_SETUP
#line 126 "emoji_flow.l"
{ output_token(AND, "AND", yytext); col_num += 1; return AND; }
	YY_BREAK
/* OR: 🔀 (U+1F500) */
case 16:
YY_RULE_SETUP
#line 129 "emoji_flow.l"
{ output_token(OR, "OR", yytext); col_num += 1; return OR; }
	YY_BREAK
/* NOT: 🚫 (U+1F6AB) */
case 17:
YY_RULE_SETUP
#line 132 "emoji_flow.l"
{ output_token(NOT, "NOT", yytext); col_num += 1; return NOT; }
	YY_BREAK
/* GT: 🔼 (U+1F53C) */
case 18:
YY_RULE_SETUP
#line 135 "emoji_flow.l"
{ output_token(GT, "GT", yytext); col_num += 1; return GT; }
	YY_BREAK
/* LT: 🔽 (U+1F53D) */
case 19:
YY_RULE_SETUP
#line 138 "emoji_flow.l"
{ output_token(LT, "LT", yytext); col_num += 1; return LT; }
	YY_BREAK
/* EQ/ASSIGN: 🟰 (U+1F7F0) */
case 20:
YY_RULE_SETUP
#line 141 "emoji_flow.l"
{ output_token(EQ, "EQ", yytext); col_num += 1; return EQ; }
	YY_BREAK
/* ============ Input / Output ============ */
/* INPUT: 📥 (U+1F4E5) */
case 21:
YY_RULE_SETUP
#line 146 "emoji_flow.l"
{ output_token(INPUT, "INPUT", yytext); col_num += 1; return INPUT; }
	YY_BREAK
/* OUTPUT: 📤 (U+1F4E4) */
case 22:
YY_RULE_SETUP
#line 149 "emoji_flow.l"
{ output_token(OUTPUT, "OUTPUT", yytext); col_num += 1; return OUTPUT; }
	YY_BREAK
/* LOG: 📝 (U+1F4DD) */
case 23:
YY_RULE_SETUP
#line 152 "emoji_flow.l"
{ output_token(LOG, "LOG", yytext); col_num += 1; return LOG; }
	YY_BREAK
/* ALERT: 🔔 (U+1F514) */
case 24:
YY_RULE_SETUP
#line 155 "emoji_flow.l"
{ output_token(ALERT, "ALERT", yytext); col_num += 1; return ALERT; }
	YY_BREAK
/* ============ File & System ============ */
/* OPEN: 📂 (U+1F4C2) */
case 25:
YY_RULE_SETUP
#line 160 "emoji_flow.l"
{ output_token(OPEN, "OPEN", yytext); col_num += 1; return OPEN; }
	YY_BREAK
/* CLOSE: 📁 (U+1F4C1) */
case 26:
YY_RULE_SETUP
#line 163 "emoji_flow.l"
{ output_token(CLOSE, "CLOSE", yytext); col_num += 1; return CLOSE; }
	YY_BREAK
/* FILE: 🧾 (U+1F9FE) */
case 27:
YY_RULE_SETUP
#line 166 "emoji_flow.l"
{ output_token(FILE_TOK, "FILE", yytext); col_num += 1; return FILE_TOK; }
	YY_BREAK
/* DELETE: ❌ (U+274C) */
case 28:
YY_RULE_SETUP
#line 169 "emoji_flow.l"
{ output_token(DELETE, "DELETE", yytext); col_num += 1; return DELETE; }
	YY_BREAK
/* WRITE: ✏️ (U+270F U+FE0F) */
case 29:
YY_RULE_SETUP
#line 172 "emoji_flow.l"
{ output_token(WRITE, "WRITE", yytext); col_num += 2; return WRITE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 173 "emoji_flow.l"
{ output_token(WRITE, "WRITE", yytext); col_num += 1; return WRITE; }
	YY_BREAK
/* READ: 📄 (U+1F4C4) */
case 31:
YY_RULE_SETUP
#line 176 "emoji_flow.l"
{ output_token(READ, "READ", yytext); col_num += 1; return READ; }
	YY_BREAK
/* ============ Time & Control ============ */
/* TIME: ⏰ (U+23F0) */
case 32:
YY_RULE_SETUP
#line 181 "emoji_flow.l"
{ output_token(TIME, "TIME", yytext); col_num += 1; return TIME; }
	YY_BREAK
/* SCHEDULE: 🕒 (U+1F552) */
case 33:
YY_RULE_SETUP
#line 184 "emoji_flow.l"
{ output_token(SCHEDULE, "SCHEDULE", yytext); col_num += 1; return SCHEDULE; }
	YY_BREAK
/* NEXT: ⏭️ (U+23ED U+FE0F) */
case 34:
YY_RULE_SETUP
#line 187 "emoji_flow.l"
{ output_token(NEXT, "NEXT", yytext); col_num += 2; return NEXT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 188 "emoji_flow.l"
{ output_token(NEXT, "NEXT", yytext); col_num += 1; return NEXT; }
	YY_BREAK
/* PREV: ⏮️ (U+23EE U+FE0F) */
case 36:
YY_RULE_SETUP
#line 191 "emoji_flow.l"
{ output_token(PREV, "PREV", yytext); col_num += 2; return PREV; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 192 "emoji_flow.l"
{ output_token(PREV, "PREV", yytext); col_num += 1; return PREV; }
	YY_BREAK
/* ============ Identifiers & Variables ============ */
/* ID marker: 📛 (U+1F4DB) */
case 38:
YY_RULE_SETUP
#line 197 "emoji_flow.l"
{ output_token(ID, "ID", yytext); col_num += 1; return ID; }
	YY_BREAK
/* INT type: 🔢 (U+1F522) */
case 39:
YY_RULE_SETUP
#line 200 "emoji_flow.l"
{ output_token(INT_TYPE, "INT_TYPE", yytext); col_num += 1; return INT_TYPE; }
	YY_BREAK
/* STRING type: 🔤 (U+1F524) */
case 40:
YY_RULE_SETUP
#line 203 "emoji_flow.l"
{ output_token(STRING_TYPE, "STRING_TYPE", yytext); col_num += 1; return STRING_TYPE; }
	YY_BREAK
/* TRUE: 🔥 (U+1F525) */
case 41:
YY_RULE_SETUP
#line 206 "emoji_flow.l"
{ output_token(TRUE_VAL, "TRUE", yytext); col_num += 1; return TRUE_VAL; }
	YY_BREAK
/* FALSE: ❄️ (U+2744 U+FE0F) */
case 42:
YY_RULE_SETUP
#line 209 "emoji_flow.l"
{ output_token(FALSE_VAL, "FALSE", yytext); col_num += 2; return FALSE_VAL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 210 "emoji_flow.l"
{ output_token(FALSE_VAL, "FALSE", yytext); col_num += 1; return FALSE_VAL; }
	YY_BREAK
/* ERROR: ⚠️ (U+26A0 U+FE0F) */
case 44:
YY_RULE_SETUP
#line 213 "emoji_flow.l"
{ output_token(ERROR_TOK, "ERROR", yytext); col_num += 2; return ERROR_TOK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 214 "emoji_flow.l"
{ output_token(ERROR_TOK, "ERROR", yytext); col_num += 1; return ERROR_TOK; }
	YY_BREAK
/* ============ Standard Tokens ============ */
/* Semicolon */
case 46:
YY_RULE_SETUP
#line 219 "emoji_flow.l"
{ output_token(SEMI, "SEMI", yytext); col_num += 1; return SEMI; }
	YY_BREAK
/* Parentheses and Braces */
case 47:
YY_RULE_SETUP
#line 222 "emoji_flow.l"
{ output_token(LPAREN, "LPAREN", yytext); col_num += 1; return LPAREN; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 223 "emoji_flow.l"
{ output_token(RPAREN, "RPAREN", yytext); col_num += 1; return RPAREN; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 224 "emoji_flow.l"
{ output_token(LBRACE, "LBRACE", yytext); col_num += 1; return LBRACE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 225 "emoji_flow.l"
{ output_token(RBRACE, "RBRACE", yytext); col_num += 1; return RBRACE; }
	YY_BREAK
/* Operators */
case 51:
YY_RULE_SETUP
#line 228 "emoji_flow.l"
{ output_token(COMMA, "COMMA", yytext); col_num += 1; return COMMA; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 229 "emoji_flow.l"
{ output_token(PLUS, "PLUS", yytext); col_num += 1; return PLUS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 230 "emoji_flow.l"
{ output_token(MINUS, "MINUS", yytext); col_num += 1; return MINUS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 231 "emoji_flow.l"
{ output_token(MULTIPLY, "MUL", yytext); col_num += 1; return MULTIPLY; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 232 "emoji_flow.l"
{ output_token(DIVIDE, "DIV", yytext); col_num += 1; return DIVIDE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 233 "emoji_flow.l"
{ output_token(COLON, "COLON", yytext); col_num += 1; return COLON; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 234 "emoji_flow.l"
{ output_token(ASSIGN, "ASSIGN", yytext); col_num += 1; return ASSIGN; }
	YY_BREAK
/* Numbers */
case 58:
YY_RULE_SETUP
#line 237 "emoji_flow.l"
{ output_token(NUMBER, "NUMBER", yytext); col_num += yyleng; return NUMBER; }
	YY_BREAK
/* String literals */
case 59:
YY_RULE_SETUP
#line 240 "emoji_flow.l"
{ output_token(STRING_LIT, "STRING", yytext); col_num += yyleng; return STRING_LIT; }
	YY_BREAK
/* Identifiers (alphanumeric after emoji markers) */
case 60:
YY_RULE_SETUP
#line 243 "emoji_flow.l"
{ output_token(IDENTIFIER, "IDENTIFIER", yytext); col_num += yyleng; return IDENTIFIER; }
	YY_BREAK
/* Whitespace handling */
case 61:
YY_RULE_SETUP
#line 246 "emoji_flow.l"
{ col_num += yyleng; /* Skip whitespace */ }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 247 "emoji_flow.l"
{ line_num++; col_num = 1; /* Track newlines */ }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 248 "emoji_flow.l"
{ /* Ignore carriage return */ }
	YY_BREAK
/* Comments: 💬 text until newline */
case 64:
YY_RULE_SETUP
#line 251 "emoji_flow.l"
{ /* Skip comments */ }
	YY_BREAK
/* Unknown characters - report as error */
case 65:
YY_RULE_SETUP
#line 254 "emoji_flow.l"
{ 
                                    fprintf(stderr, "Warning: Unknown character '%s' at line %d, col %d\n", 
                                            yytext, line_num, col_num);
                                    col_num += 1;
                                }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 260 "emoji_flow.l"
ECHO;
	YY_BREAK
#line 1181 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 113 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 113 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 112);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 260 "emoji_flow.l"


int main(int argc, char **argv) {
    if (argc < 2) {
        fprintf(stderr, "Usage: %s <input_file> [output_file]\n", argv[0]);
        fprintf(stderr, "  input_file  : EMOJI-FLOW source file (.emoji or .ef)\n");
        fprintf(stderr, "  output_file : Token output file (default: tokens.txt)\n");
        return 1;
    }

    FILE *input_file = fopen(argv[1], "r");
    if (!input_file) {
        fprintf(stderr, "Error: Cannot open input file '%s'\n", argv[1]);
        return 1;
    }

    const char *output_filename = (argc >= 3) ? argv[2] : "tokens.txt";
    output_file = fopen(output_filename, "w");
    if (!output_file) {
        fprintf(stderr, "Error: Cannot create output file '%s'\n", output_filename);
        fclose(input_file);
        return 1;
    }

    printf("==============================================\n");
    printf("  EMOJI-FLOW Lexical Analyzer v1.0\n");
    printf("  Input:  %s\n", argv[1]);
    printf("  Output: %s\n", output_filename);
    printf("==============================================\n\n");

    /* Write header to output file */
    fprintf(output_file, "# EMOJI-FLOW Token Stream\n");
    fprintf(output_file, "# Generated from: %s\n", argv[1]);
    fprintf(output_file, "# Format: TOKEN_TYPE LEXEME\n\n");

    yyin = input_file;
    
    /* Tokenize the input */
    while (yylex());

    printf("\n==============================================\n");
    printf("  Lexical analysis complete!\n");
    printf("  Total lines processed: %d\n", line_num);
    printf("  Output written to: %s\n", output_filename);
    printf("==============================================\n");

    fclose(input_file);
    fclose(output_file);

    return 0;
}
